version: '3.8'

services:
    shafasrm-postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - shafasrm-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U shafasrmadmin -d shafasrm"]
        interval: 5s
        timeout: 5s
        retries: 5
    
    migrations:
      build:
        context: .
        dockerfile: Dockerfile.migration
      networks:
        - shafasrm-network
      environment:
        GOOSE_DRIVER: ${GOOSE_DRIVER}
        GOOSE_DBSTRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}
      depends_on:
        shafasrm-postgres:
          condition: service_healthy
    
    app:
      build:
        context: .
        dockerfile: Dockerfile.app
      networks:
        - shafasrm-network
      environment:
          POSTGRES_HOST: ${POSTGRES_HOST}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
          APISECRET: ${APISECRET}
          IAMUSERACCESSKEY: ${IAMUSERACCESSKEY}
          IAMUSERSECRET: ${IAMUSERSECRET}
          S3BUCKETNAME: ${S3BUCKETNAME}
          S3BUCKETREGION: ${S3BUCKETREGION}
          PORT: ${PORT}
          ENVIRONMENT: ${ENVIRONMENT}

      ports:
        - "3000:3000"
      depends_on:
        migrations:
          condition: service_completed_successfully

networks:
  shafasrm-network:
    external: true

volumes:
  postgres-data:
