FROM alpine:3.21

RUN apk --no-cache add curl ca-certificates

WORKDIR /app

RUN curl -L https://github.com/pressly/goose/releases/download/v3.24.2/goose_linux_x86_64 -o /usr/local/bin/goose && chmod +x /usr/local/bin/goose

COPY /internal/database/migrations /app/migrations

CMD ["sh", "-c", "goose -dir /app/migrations up"]